  units           real
  atom_style      full
  bond_style      harmonic
  angle_style     harmonic
  dihedral_style  opls
  pair_style      lj/cut 9.0
  # If you have charged molecules immersed in a salty implicit
  # solvent, you might try something like this this instead:
  #    pair_style      lj/cut/coul/debye 0.1 9.0
  pair_modify     mix arithmetic
  dielectric      80.0
  special_bonds   lj 0.0 0.0 0.0
